# Generated by Django 4.2.4 on 2023-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='version',
            field=models.CharField(choices=[('v1', 'Version 1'), ('v2', 'Version 2')], max_length=10),
        ),
    ]
